workflows:
  android-workflow:
    name: finstudent – Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: 20
      java: 17
      vars:
        APP_NAME: finstudent

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Web App
        script: |
          # Agar Vite / React use ho raha hai
          npm run build || echo "No build script found"
          ls -la dist || ls -la build

      - name: Ensure Android platform
        script: |
          npx cap add android || echo "Android already exists"

      - name: Sync Capacitor (icons, config, assets)
        script: |
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
